import React, { useState, useEffect } from "react";
import { Loader, Card, FormField } from "../components";

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllosts] = useState(null);
  return (
    <section className="max-w-7xl mx-auto">
      <h1 className="font-extrabold text-[#222328] text-[32px]">
        The Community Showcase
      </h1>
      <p className="mt-2 text-[#66e75] text-[16px] max-w-[500px]">
        Browse Through a Collection of Imaginitave and visually stunning images
        generated by Dall-E AI
      </p>
      <div className="mt-16">
        <FormField/>
      </div>
      <div className="mt-10">
        {loading ? (
            <div className="flex justify-center items-center">
                <Loader/>
            </div>
        ) : (
            <></>
        )}
      </div>
    </section>
  );
};

export default Home;
